# Generated by Django 3.1 on 2020-08-22 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('difficulty', models.CharField(choices=[('Low', 'Low Priority Task'), ('Moderate', 'Medium Priority Task'), ('High', 'High Priority Task')], default='Moderate', max_length=32)),
                ('time', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
            ],
        ),
    ]
