# Generated by Django 3.1 on 2020-08-22 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='coin_value',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.PositiveIntegerField(choices=[(1, 'Low Priority Task'), (2, 'Medium Priority Task'), (4, 'High Priority Task')], default=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
