# Generated by Django 3.1 on 2020-08-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_auto_20200822_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
    ]
