# Generated by Django 3.1 on 2020-08-23 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_remove_task_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(9999999)])),
                ('items', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.PositiveIntegerField(choices=[(1, 'Low Priority Task'), (2, 'Medium Priority Task'), (4, 'High Priority Task')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
