# Generated by Django 3.1 on 2020-08-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0004_auto_20200822_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='links',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=7),
        ),
    ]
